#! /bin/bash

set -e # stop on error

templates_top_dir="gitignore"

if [ "$1" != "" ]; then
    out_file="$1"
else
    out_file=/dev/stdout
fi

include_gitignore () {
    local  in_file="$1"
    local out_file="$2"
    if [ -s "$in_file" ]; then
        local filename="`basename "$in_file"`"
        (
        echo "# **************************************************"
        echo "# $filename"
        echo "# **************************************************"
        echo
        cat "$in_file"
        echo
        echo
        ) >> "$out_file"
    fi
}

include_gitignores () {
    local list_file="$1$2"
    local template_dir="$3"
    local out_file="$4"
    if [ -s "$list_file" ]; then
        while read name; do
            if [ -z "$line" ] || [ "${line:0:1}" == "#" ]; then continue; fi
            local name="$line"
            local in_file="$templates_top_dir/$template_dir/$name.gitignore"
            include_gitignore "$in_file" "$out_file"
        done < "$list_file"
   #else
   #    for name in "$templates_top_dir/$template_dir"/*.gitignore; do
   #        include_gitignore "$name" "$out_file"
   #    done
    fi
}

# initialize
echo >| $out_file

include_gitignore  "repository.gitignore" "$out_file"
include_gitignores  "local.lst" .         "$out_file"
include_gitignores "global.lst" Global    "$out_file"
