#! /bin/bash

set -e # stop on error

templates_top_dir="gitignore"

if [ "$1" != "" ]; then
    out_file="`readlink -f "$1"`"
else
    out_file=/dev/stdout
fi

include_gitignore () {
    local  in_file="$1"
    local out_file="$2"
    if [ -f "$in_file" ]; then
        local filename="`basename "$in_file"`"
        (
        echo "# **************************************************"
        echo "# $filename"
        echo "# **************************************************"
        echo
        cat "$in_file"
        echo
        echo
        ) >> "$out_file"
    fi
}

include_gitignores () {
    local list_file="$1"
    local template_dir="$2"
    local out_file="$3"
    if [ -f "$list_file" ]; then
        while read line; do
            if [ -z "$line" ] || [ "${line:0:1}" == "#" ]; then continue; fi
            local name="$line"
            local in_file="$templates_top_dir/$template_dir/$name.gitignore"
            include_gitignore "$in_file" "$out_file"
        done < "$list_file"
    fi
}

change_working_dir () {
    local script_path="`readlink -f "$0"`"
    local script_dir="`dirname "$script_path"`"
    local working_dir="`dirname "$script_dir"`"
    cd "$working_dir"
}

change_working_dir

# initialize
echo >| $out_file

include_gitignore  "repository.gitignore" "$out_file" # for  local gitignore
include_gitignore        "user.gitignore" "$out_file" # for global gitignore
include_gitignores  "local.lst" .         "$out_file" # for  local gitignore
include_gitignores "global.lst" Global    "$out_file" # for global gitignore
